
server:
  port: 80
  env: dev
  region: SG

redis:
  host: 127.0.0.1
  port: 6379
  username: "default"
  password: ali123
  db: 0
  queueDB: 1

mysql:
  host: localhost
  port: 3306
  username: root
  password: pass123
  db: flat_server

jwt:
  secret: "3f7b2e9c1a5d8f4b6e0c2a9d7b1e5f8c3d6a0e9b4c7f2d5a8e1b3c6f9d2e7a4"
  algorithms: 'HS256'
# website: https://flat-web-dev.whiteboard.agora.io
website: https://localhost:3000

default_avatar: https://flat-storage.oss-cn-hangzhou.aliyuncs.com/flat-resources/avatar/[index].png

# flag see: https://github.com/netless-io/flat-server/blob/main/src/utils/EnvVariable.ts
log:
  pathname: "{{PROJECT_DIR}}/logs"
  filename: "{{DAY_DATE}}"

cloud_storage:
  # upload concurrent (default: 3)
  concurrent: 3
  # default: 500M
  single_file_size: 524288000
  # default: 2G
  total_size: 2147483648
  # storage service prefix path (default: cloud-storage)
  prefix_path: cloud-storage
  allow_file_suffix:
    - ppt
    - pptx
    - doc
    - docx
    - pdf
    - png
    - jpg
    - jpeg
    - gif
    - mp3
    - mp4
  temp_photo:
    # max single file size: 5M
    single_file_size: 5242880
    # max files per day per user: 60
    total_files: 60
    prefix_path: cloud-storage/temp-photo
    allow_suffix:
      - png
      - jpg
      - jpeg

user:
  avatar:
    # 5M
    size: 5242880
    allow_suffix:
      - png
      - jpg
      - jpeg

oauth:
  logo:
    prefix_path: oauth-logo
    size: 5242880
    allow_suffix:
      - png
      - jpg
      - jpeg


login:
  salt: "3f7b2e9c1a5d8f4b6e0c2a9d7b1e5f8c3d6a0e9b4c7f2d5a8e1b3c6f9d2e7a4"
  wechat:
    web:
      enable: false
      app_id:
      app_secret:
    mobile:
      enable: false
      app_id:
      app_secret:
  github:
    enable: false
    client_id:
    client_secret:
  google:
    enable: false
    client_id:
    client_secret:
    redirect_uri:
      login:
      bind:
  apple:
    enable: false
  agora:
    enable: false
    client_id:
    client_secret:
  sms:
    enable: true
    force: false
    test_users: 
      - phone: "+923154604802"
        code: "012345"
    chinese_mainland:
      access_id:
      access_secret:
      template_code:
      sign_name:
    # hmt(Hong Kong, Macao and Taiwan regions of China)
    hmt:
      access_id:
      access_secret:
      template_code:
      sign_name:
    global:
      access_id:
      access_secret:
      template_code:
      sign_name:
  email:
    enable: true
    test_emails:
      - email:
        code:
    type: smtp
    smtp:
      host: smtp-relay.brevo.com
      port: 587
      secure: false
      auth:
        user: 8ae744001@smtp-brevo.com
        pass: fsrzkTbKnJ9y0UPW

    aliCloud:
      access_id:
      access_secret:
      account_name: test@test.test

apple:
  app_id: 48TB6ZZL5S.io.agora.flat

agora:
  app:
    id: "22fe39ad172744f5a9e585b500213fd5"
    certificate: "c16fc2c533d141618f7669ef8385a708"
  restful:
    id: 
    secret:
  oss:
    access_id:
    access_secret:
    vendor:
    region:
    bucket:
    folder:
    prefix:
  screenshot:
    enable: false
    oss:
      access_id:
      access_secret:
      vendor:
      region:
      bucket:
      folder:
      prefix:
  messageNotification:
    enable: false
    events:
      - productID:
        eventType:
        secret:
  ai:
    server_cn: "http://43.131.39.44:8082"
    server_en: "http://43.131.39.44:8081"

whiteboard:
  app_id: "ptg2wOleEe-n__HYKx8QBQ/BkCNyhYO8Revwg"
  access_key: "j-buTYIgsmhHL0Qr"
  secret_access_key: "mJm7RzKQFb8Lh_ZN_EKdBhelogKAEmhV"
  region: "sg"
  convert_region:  "sg"

storage_service:
  type: oss
  oss:
    access_key: "myadminMinio"          # MINIO_ROOT_USER
    secret_key: "RootPass123" # MINIO_ROOT_PASSWORD
    accessKey: "myadminMinio"          # MINIO_ROOT_USER
    accessKeySecret: "RootPass123" # MINIO_ROOT_PASSWORD
    endpoint: http://127.0.0.1:9000
    bucket: flat
    region: us-east-1
    signature_version: "v4"
    secure: false
    cname: false
    # path_style: true 

# storage_service:
#   type: oss
#   oss:
#     access_key: "LTAI5tCR12974x9jSFrr95hT"
#     secret_key: "FVG6cLjpUnRM96dIqc4xgNhg0DALxn"
#     endpoint: oss-cn-beijing.aliyuncs.com 
#     bucket: flat
#     region: China Beijing
censorship:
  video:
    enable: false
    type: aliCloud
    aliCloud:
      uid:
      access_id:
      access_secret:
      endpoint:
  voice:
    enable: false
    type: aliCloud
    aliCloud:
      uid:
      access_id:
      access_secret:
      callback_address:
  text:
    enable: false
    type: aliCloud
    aliCloud:
      access_id:
      access_secret:
      endpoint:

admin:
  secret:
